```swift
do {
    try await Amplify.DataStore.clear()
    print("DataStore cleared")
} catch let error as DataStoreError {
    print("Error clearing DataStore: \(error)")
} catch {
    print("Unexpected error \(error)")
}
```
