```dart
Future<void> confirmSignIn(String generatedNumber) async {
  try {
    final result = await Amplify.Auth.confirmSignIn(
      /// Enter the random number generated by your Create Auth Challenge trigger
      confirmationValue: generatedNumber,
    );
    safePrint('Sign in result: $result');
  } on AuthException catch (e) {
    safePrint('Error signing in: $\{e.message}');
  }
}
```

Once the user provides the correct response, they should be authenticated in your application.

<Callout warning>

<b>Special Handling on ConfirmSignIn</b>

During a `confirmSignIn` call, if `failAuthentication: true` is returned by the Lambda, the session of the request gets invalidated by Cognito, and a `NotAuthorizedException` is thrown. To recover, the user must initiate a new sign in by calling `Amplify.Auth.signIn`.

Exception: `NotAuthorizedException` with a message `Invalid session for the user.`

</Callout>
